# Grafana Datasource Configuration
# Agent Epsilon - Production Monitoring Specialist

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      manageAlerts: true
      alertmanagerUid: alertmanager
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger
    secureJsonData: {}

  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          matcherRegex: "trace_id=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: jaeger

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: xai_trading
    user: xai_user
    secureJsonData:
      password: ${XAI_DB_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1500
      timescaledb: false

deleteBeforeMigration: false