# SHARED GOOGLE COLAB PRO OPTIMIZATION CONFIGURATION
# Version: 1.0
# Last Updated: 2025-07-20

# Colab Environment Configuration
colab_environment:
  runtime_type: "GPU"
  gpu_type: "T4"  # or "V100" if available
  ram_gb: 25.5
  disk_gb: 108
  python_version: "3.10"
  
# GPU Optimization Settings
gpu_optimization:
  mixed_precision: true
  tensor_core_usage: true
  memory_growth: true
  memory_limit_fraction: 0.9
  allow_growth: true
  
  # Memory management
  clear_cache_frequency: 100  # Clear GPU cache every N steps
  gradient_checkpointing: true
  model_parallelism: false
  data_parallelism: false

# Memory Optimization
memory_optimization:
  batch_size_strategy: "adaptive"
  gradient_accumulation_steps: 4
  dataloader_num_workers: 2
  pin_memory: true
  persistent_workers: true
  
  # Terminal-specific memory allocation
  terminal_1_memory_gb: 12
  terminal_2_memory_gb: 13
  
  # Memory monitoring
  memory_monitoring: true
  oom_prevention: true
  auto_memory_cleanup: true

# Training Optimization
training_optimization:
  # Learning rate scheduling
  learning_rate_scheduler: "cosine_annealing"
  warmup_steps: 1000
  min_learning_rate: 1e-6
  
  # Batch processing
  dynamic_batching: true
  batch_size_finder: true
  max_batch_size: 512
  min_batch_size: 16
  
  # Gradient optimization
  gradient_clipping: true
  gradient_norm_threshold: 1.0
  optimizer: "AdamW"
  weight_decay: 0.01

# Checkpoint Management
checkpoint_management:
  auto_save: true
  save_frequency: 500  # Save every N steps
  max_checkpoints_to_keep: 5
  checkpoint_compression: true
  
  # Google Drive integration
  drive_backup: true
  drive_sync_frequency: 1000  # Sync to Drive every N steps
  drive_path: "/content/drive/MyDrive/GrandModel_Checkpoints"
  
  # Terminal-specific checkpoint paths
  terminal_1_checkpoints: "/content/drive/MyDrive/GrandModel_Checkpoints/terminal_1"
  terminal_2_checkpoints: "/content/drive/MyDrive/GrandModel_Checkpoints/terminal_2"

# Data Pipeline Optimization
data_pipeline:
  prefetch_factor: 2
  cache_size_gb: 5
  data_loading_workers: 4
  
  # Data caching strategy
  cache_training_data: true
  cache_validation_data: true
  use_memory_mapped_files: true
  
  # Data preprocessing
  precompute_features: true
  normalize_on_the_fly: false
  augmentation_probability: 0.1

# Colab-Specific Optimizations
colab_optimizations:
  # Session management
  keep_alive_interval: 3600  # Ping every hour to prevent disconnection
  auto_reconnect: true
  session_timeout_hours: 12
  
  # Resource monitoring
  resource_monitoring_interval: 300  # Check resources every 5 minutes
  auto_resource_optimization: true
  performance_profiling: true
  
  # Display optimizations
  reduce_output_verbosity: true
  progress_bar_update_interval: 100
  plot_update_frequency: 1000

# Terminal Coordination for Colab
terminal_coordination:
  # Shared Drive folders
  shared_drive_root: "/content/drive/MyDrive/GrandModel_Coordination"
  
  coordination_folders:
    progress: "/content/drive/MyDrive/GrandModel_Coordination/progress"
    checkpoints: "/content/drive/MyDrive/GrandModel_Coordination/checkpoints"
    logs: "/content/drive/MyDrive/GrandModel_Coordination/logs"
    data: "/content/drive/MyDrive/GrandModel_Coordination/data"
  
  # File synchronization
  sync_strategy: "periodic"
  sync_interval_minutes: 15
  conflict_resolution: "timestamp_based"
  
  # Cross-terminal communication
  status_file_updates: true
  dependency_checking: true
  resource_coordination: true

# Performance Monitoring
performance_monitoring:
  track_gpu_utilization: true
  track_memory_usage: true
  track_training_speed: true
  track_model_performance: true
  
  # Metrics collection
  metrics_collection_interval: 60  # seconds
  performance_logging: true
  automatic_reporting: true
  
  # Performance targets
  target_gpu_utilization: 0.85
  target_memory_utilization: 0.8
  target_training_speed_samples_per_second: 1000

# Notebook-Specific Configurations
notebook_configs:
  risk_management:
    terminal: "terminal_1"
    priority: "high"
    gpu_memory_limit_gb: 4
    estimated_training_time_hours: 2
    
  execution_engine:
    terminal: "terminal_1" 
    priority: "high"
    gpu_memory_limit_gb: 3
    estimated_training_time_hours: 1.5
    
  xai_explanations:
    terminal: "terminal_1"
    priority: "medium"
    gpu_memory_limit_gb: 5
    estimated_training_time_hours: 3
    
  strategic_training:
    terminal: "terminal_2"
    priority: "critical"
    gpu_memory_limit_gb: 8
    estimated_training_time_hours: 4
    
  tactical_training:
    terminal: "terminal_2"
    priority: "high" 
    gpu_memory_limit_gb: 5
    estimated_training_time_hours: 2.5

# Error Handling and Recovery
error_handling:
  auto_retry_on_oom: true
  retry_attempts: 3
  backoff_strategy: "exponential"
  
  # Error recovery
  checkpoint_recovery: true
  auto_fallback_batch_size: true
  graceful_degradation: true
  
  # Notification system
  error_notifications: true
  success_notifications: false
  milestone_notifications: true

# Quality Assurance
quality_assurance:
  validation_frequency: 500
  model_validation: true
  performance_regression_detection: true
  
  # Testing integration
  unit_test_frequency: 1000
  integration_test_frequency: 5000
  performance_test_frequency: 10000