# Model Architecture Configurations for AlgoSpace Training

# RDE Model Configuration
rde:
  input_dim: 155
  hidden_dim: 256
  latent_dim: 8
  num_heads: 8
  num_layers: 3
  dropout: 0.1
  learning_rate: 1e-4
  batch_size: 32

# M-RMS Configuration
mrms:
  input_dim: 40
  hidden_dim: 128
  output_dims:
    position_sizing: 1
    stop_loss: 1
    profit_target: 1
  learning_rate: 2e-4
  batch_size: 64

# Main MARL Core Configuration
main_core:
  embedder_configs:
    structure:
      input_channels: 8
      output_dim: 64
      dropout: 0.2
    tactical:
      input_channels: 7
      output_dim: 48
      dropout: 0.2
    regime:
      input_dim: 8
      output_dim: 16
    lvn:
      input_dim: 5
      output_dim: 8
  
  shared_policy:
    input_dim: 136  # 64+48+16+8
    hidden_dim: 256
    output_dim: 2
    dropout: 0.3
  
  decision_gate:
    input_dim: 144  # unified_state + policy_output
    hidden_dim: 64
    dropout: 0.2
  
  learning_rate: 3e-4
  batch_size: 128

# Training Parameters
training:
  epochs: 200
  patience: 20
  min_delta: 0.001
  device: "cuda"
  seed: 42