# Parallel MARL System Configuration
# 8 Agent Architecture: 4 Strategic + 4 Tactical

system:
  name: "ParallelMARLSystem"
  total_agents: 8
  max_velocity_mode: true
  trustworthiness_target: 3.0  # 300%

# Matrix Assembler Configuration
matrix_assemblers:
  30m:
    name: "MatrixAssembler30m"
    window_size: 48
    features:
      - mlmi_value
      - mlmi_signal
      - nwrqk_value
      - nwrqk_slope
      - lvn_distance_points
      - lvn_nearest_strength
      - time_hour_sin
      - time_hour_cos
      - mmd_pc1  # MMD Principal Component 1
      - mmd_pc2  # MMD Principal Component 2
      - mmd_pc3  # MMD Principal Component 3
    
    # MMD Configuration
    mmd_config:
      window_size: 100
      method: "pca"  # or "tsne"
      update_frequency: 10
    
    normalization:
      method: rolling_zscore
      window: 100
    
    validation:
      enabled: true
      max_nan_ratio: 0.05
      
  5m:
    name: "MatrixAssembler5m"
    window_size: 60
    features:
      - fvg_bullish_active
      - fvg_bearish_active
      - fvg_nearest_level
      - fvg_age
      - fvg_mitigation_signal
      - price_momentum_5
      - volume_ratio
    
    normalization:
      method: minmax
      clip_outliers: true
    
    performance:
      max_assembly_time_ms: 0.5
      enable_caching: true

# Agent Configuration
agents:
  strategic:
    count: 4
    timeframe: "30m"
    matrix_type: "30m"
    decision_type: "strategic"
    
    agents:
      - id: "strategic_1"
        specialization: "trend_following"
        risk_tolerance: 0.8
        
      - id: "strategic_2"
        specialization: "mean_reversion"
        risk_tolerance: 0.6
        
      - id: "strategic_3"
        specialization: "momentum"
        risk_tolerance: 0.9
        
      - id: "strategic_4"
        specialization: "structure_analysis"
        risk_tolerance: 0.7
    
    performance:
      max_decision_time_ms: 5.0
      confidence_threshold: 0.3
      
  tactical:
    count: 4
    timeframe: "5m"
    matrix_type: "5m"
    decision_type: "tactical"
    
    agents:
      - id: "tactical_1"
        specialization: "scalping"
        execution_speed: "ultra_fast"
        
      - id: "tactical_2"
        specialization: "breakout"
        execution_speed: "fast"
        
      - id: "tactical_3"
        specialization: "pullback"
        execution_speed: "fast"
        
      - id: "tactical_4"
        specialization: "risk_management"
        execution_speed: "immediate"
    
    performance:
      max_decision_time_ms: 1.0
      urgency_levels: ["low", "high", "immediate"]

# Event System Configuration
events:
  matrix_events:
    - MATRIX_30M_READY
    - MATRIX_5M_READY
    
  agent_events:
    - STRATEGIC_DECISION
    - TACTICAL_DECISION
    - AGENT_ACKNOWLEDGMENT
    
  validation_events:
    - MATRIX_VALIDATION_FAILED
    - DELIVERY_CONFIRMED
    
  buffer_size: 10000
  processing_timeout_ms: 100

# Matrix Delivery Validation
delivery_validation:
  enabled: true
  triple_validation: true
  
  integrity_checks:
    - matrix_not_null
    - shape_validation
    - finite_values_check
    - range_validation
    
  delivery_confirmation:
    timeout_ms: 1000
    retry_attempts: 3
    
  agent_acknowledgment:
    required: true
    timeout_ms: 500

# Performance Monitoring
monitoring:
  metrics_collection: true
  real_time_dashboard: true
  
  performance_targets:
    matrix_assembly_time_ms: 1.0
    agent_decision_time_ms: 5.0
    delivery_success_rate: 0.99
    acknowledgment_rate: 0.99
    system_uptime: 0.999
    
  alerts:
    - type: "performance_degradation"
      threshold: 0.95
      
    - type: "delivery_failure"
      threshold: 0.98
      
    - type: "agent_error_rate"
      threshold: 0.02

# Trustworthiness Configuration
trustworthiness:
  target_score: 3.0  # 300%
  
  components:
    delivery_reliability: 1.0
    agent_acknowledgment: 1.0  
    system_health: 1.0
    
  monitoring:
    update_frequency_ms: 1000
    alert_threshold: 2.5  # Below 250%
    
  recovery:
    auto_restart_agents: true
    matrix_replay_buffer: 10
    emergency_fallback: true

# Parallel Processing
parallel_processing:
  async_execution: true
  max_concurrent_decisions: 8
  agent_isolation: true
  
  threading:
    agent_threads: 8
    matrix_processing_threads: 2
    validation_threads: 1
    
  memory_management:
    max_matrix_cache_mb: 100
    decision_history_size: 1000
    gc_frequency_seconds: 60

# Logging Configuration
logging:
  level: "INFO"
  
  loggers:
    - name: "ParallelMARLSystem"
      level: "INFO"
      
    - name: "MatrixDeliveryValidator"
      level: "DEBUG"
      
    - name: "ParallelAgent"
      level: "INFO"
      
    - name: "MMDProcessor"
      level: "DEBUG"
      
  performance_logging:
    decision_times: true
    matrix_stats: true
    delivery_metrics: true

# Development/Testing Overrides
development:
  reduced_window_sizes: false
  mock_decisions: false
  debug_matrix_content: false
  validate_all_decisions: true
  
  test_mode:
    enabled: false
    synthetic_matrices: false
    agent_simulation: false