# Development Environment Configuration Overrides

system:
  environment: development
  ssl_enabled: false
  backup_enabled: true
  debug: true
  log_level: DEBUG

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:grandmodel_dev}
  username: ${DB_USERNAME:grandmodel_dev}
  password: ${SECRET:db_password_dev}
  ssl_mode: disable
  connection_pool:
    min_connections: 2
    max_connections: 20

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${SECRET:redis_password_dev}
  ssl: false
  cluster_enabled: false

security:
  jwt_secret_key: ${SECRET:jwt_secret_dev}
  api_rate_limit: 10000
  cors_origins: ["http://localhost:3000", "http://localhost:8080"]
  encryption_key: ${SECRET:encryption_key_dev}

monitoring:
  prometheus_port: 9091
  enable_profiling: true
  metrics_interval: 30
  health_check_interval: 10

risk_management:
  max_position_size: 100000
  max_daily_loss: 5000
  max_drawdown_percent: 10
  stop_loss_percent: 2.0
  position_sizing_method: "fixed"
  var_confidence: 0.95

data_handler:
  type: "backtest"
  backtest_file: "data/historical/NQ - 30 min - ETH.csv"
  replay_speed: 0  # As fast as possible
  
execution:
  order_type: "market"
  slippage_ticks: 1
  commission_per_contract: 0  # No commission for development
  max_order_size: 5
  timeout_seconds: 10

logging:
  level: DEBUG
  format: pretty
  handlers:
    - console
    - file
  file:
    path: logs/development.log
    max_size: 10MB
    backup_count: 5